### ISSUE TITLE
Layout modification

### ISSUE THREAD

**Issue by Procyon-b** [FlowerForWar/was-about-that-old-in-that-movie#1]
IMDb just modified the html structure of the top banner (containing the title, type, release date, ...)

The type (film or series) is not the first element of its type anymore. This query selector should work:
line 26
```
if (document.querySelector('.ipc-inline-list.ipc-inline-list--show-dividers[data-testid="hero-title-block__metadata"]').textContent.startsWith('TV')) {
```

**Comment by JenieX** [comment]
> IMDb just modified the html structure of the top banner (containing the title, type, release date, ...)
> 
> The type (film or series) is not the first element of its type anymore. This query selector should work: line 26
> 
> ```
> if (document.querySelector('.ipc-inline-list.ipc-inline-list--show-dividers[data-testid="hero-title-block__metadata"]').textContent.startsWith('TV')) {
> ```

Thank you for catching that. Will add it in the next update.
