### ISSUE TITLE
Dealing with incomplete birth date

### ISSUE THREAD

**Issue by Procyon-b** [FlowerForWar/was-about-that-old-in-that-movie#2]
Incomplete birth dates are encoded as `datetime="1986-0-0"` which is not accepted by Date() when a string is used to initialize.
There is a simple solution by adding `.replace(/-0/g,'-1')` but then the zodiac sign is wrong. So here is what I use for the moment:
```
[...]
		const actorDates = [];
		const actorDatesFixed = [];
		var fixed=false;
		responseText.replace(/datetime="(\d{4}-\d{1,2}-\d{1,2})"/g, (match, date) => {actorDates.push(date), actorDatesFixed.push(date.replace(/-0/g,'-1'))} );
		if (actorDates[0] != actorDatesFixed[0]) fixed=true;
		const [actorBirthDate, actorDeathDate] = fixed ? actorDatesFixed : actorDates;
[...]
		span.innerHTML = `Was about ${actorInfo['age-when-the-movie-first-released']} years old` + (zodiac_signs_disabled || fixed ? '' : ` <br>(${getZodiacSign(month, day)})`);
[...]
```

**Comment by JenieX** [comment]
I thought about it before actually, but I kind of wanted to be as accurate as possible, specially when calculating the actor age at the moment of viewing. The script already assumes the movie gets released once it is done shooting. Would be ideal to have the date in which they started shooting that movie, I guess 😄.

**Comment by Procyon-b** [comment]
I often wondered the age of the actor at the time of filming. Even more when on imdb the picture assigned to the actor is one of an old person. That's when your userscript is useful.

But then, there is this film: https://www.imdb.com/title/tt1065073/
it took 12 years to shoot.   :)

**Comment by JenieX** [comment]
That just complicates things. That movie looks interesting though, will have to watch it someday.
