### ISSUE TITLE
Alternative url to prevent actors added to "Recently Viewed"

### ISSUE THREAD

**Issue by Procyon-b** [FlowerForWar/was-about-that-old-in-that-movie#3]
Fetching the actor's main page adds it to the "Recently Viewed" list at the bottom of the page.
Apparently the `/bio` page doesn't trigger that.
Your code already works. Only the url has to be modified.
I'm using this to sanitize the path (the trailing `/` is sometimes present):
```
const response = await fetch(siblingElement.firstElementChild.href.split('?')[0].replace(/\/$/,'')+'/bio');
```

**Comment by JenieX** [comment]
Good idea, will add it for sure.
